services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - 5433:5433
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
